// generated by build_3d.py on 2026-10-05 - do not edit by hand
window.REEF_MODEL = {
 "slug": "prattes-reef-el-segundo",
 "name": "Pratte's Reef (permit name: Chevron Reef), El Segundo / Dockweiler Beach, California",
 "generated": "2026-10-05",
 "caption": "Pratte's Reef (permit name Chevron Reef), El Segundo / Dockweiler Beach, California. MODELLED: Phase I as built (22 Sept 2000) - footprint = Skelly Engineering design layout of 110 bags (no as-built plan exists; the 2003 monitoring paper reprints the same design drawing), top at the as-installed depth of about 6 ft below MLLW. NOT MODELLED: Phase II (23-24 April 2001, +90 bags, crest widened and raised, eroded again by 2002) and the removal (fall 2008 and fall 2010). Seabed = NOAA DEM, checked against Navionics and the paper's profiles. Position inferred from the paper's survey window (+-100 m).",
 "lifecycle": [
  {
   "date": "1996-1998",
   "event": "concept of about 30 large bags (150 ft wings); CCC permit E-98-15 heard 13 Oct 1998",
   "source": "S1"
  },
  {
   "date": "22 Sept 2000",
   "event": "Phase I installed: 110 sand-filled geotextile bags (4 x 7 x 10 ft, 7.9 m3 max each, 80-90 % filled, about 14 t) filled at the Port of Los Angeles and placed by barge crane in a V with the apex offshore; outermost point approximately 6 ft below MLLW. THE STATE MODELLED HERE",
   "source": "S10 p.2"
  },
  {
   "date": "Oct 2000",
   "event": "first bathymetric survey (Fig. 9 contours, georeferenced); November 2000 profile taken before any significant swell",
   "source": "S10"
  },
  {
   "date": "winter 2000-01",
   "event": "Phase I bags largely covered by sand that moved offshore",
   "source": "S10 p.3"
  },
  {
   "date": "23-24 Apr 2001",
   "event": "Phase II: 90 more bags placed directly over Phase I, volume +80 %, crest widened and made shallower to within 3 ft of MLLW (NOT modelled)",
   "source": "S10 p.3"
  },
  {
   "date": "May 2001 - Sept 2002",
   "event": "crest of the widened reef eroded by about 1.5 m (Fig. 8); by Oct 2002 the bags were mostly level with the sand",
   "source": "S10 Fig. 8, p.16"
  },
  {
   "date": "Aug 2002",
   "event": "dive survey: several bags ripped and losing fill (polypropylene black bags worse than polyester white bags)",
   "source": "S10 p.8-9; S2"
  },
  {
   "date": "fall 2008",
   "event": "removal begun (30 Sept-17 Oct 2008): mostly buried remnants",
   "source": "S2, S9"
  },
  {
   "date": "fall 2010",
   "event": "removal completed (end of the 10-year permit); first removal of a purpose-built surfing reef",
   "source": "S9"
  }
 ],
 "state_label": "Phase I as built (22 Sept 2000): footprint = Skelly Engineering design layout (110 solid-outline bags; no as-built plan exists), top = as-installed depth of about 6 ft below MLLW (Borrero & Nelsen 2003); Phase II and the removal are not modelled",
 "frame": {
  "units": "m",
  "x": "alongshore toward 155 deg (SSE)",
  "y": "offshore toward 245 deg (WSW) = x turned 90 deg clockwise",
  "z": "up, 0 = MSL (NOAA 9410840, epoch 1983-2001)",
  "x_bearing_deg": 155.0,
  "y_bearing_deg": 245.0,
  "north_xy": [
   -0.9063,
   -0.4226
  ],
  "handedness_note": "(x, y, z-up) is left-handed (y = x turned CLOCKWISE); the viewer maps model (x, y, z) to three.js (X = x, Y = z, Z = y), which is mirror-free"
 },
 "plan": {
  "status": "verified",
  "verified_on": "2026-10-04",
  "shape_json_updated": "2026-10-05",
  "shape_json_md5": "2ce341598d22b61dac771292388e8935",
  "shape_json_mtime": "2026-10-05T19:24:40",
  "confidence_plan": "medium",
  "area_m2": 435.2,
  "bbox_m": {
   "alongshore": 58.0,
   "crossshore": 28.6
  },
  "max_dim_m": 58.0,
  "distance_offshore_m": 91.44,
  "n_vertices": 76,
  "polygon_xy_m": [
   [
    -6.28,
    103.27
   ],
   [
    -4.77,
    103.28
   ],
   [
    -4.25,
    102.98
   ],
   [
    -3.53,
    103.28
   ],
   [
    -2.02,
    103.28
   ],
   [
    -1.38,
    102.96
   ],
   [
    -0.66,
    103.27
   ],
   [
    0.86,
    103.26
   ],
   [
    1.51,
    102.84
   ],
   [
    2.14,
    103.25
   ],
   [
    3.84,
    103.23
   ],
   [
    4.42,
    102.84
   ],
   [
    5.0,
    103.22
   ],
   [
    6.76,
    103.21
   ],
   [
    7.82,
    102.42
   ],
   [
    8.49,
    102.48
   ],
   [
    8.6,
    102.16
   ],
   [
    7.98,
    101.31
   ],
   [
    8.04,
    100.85
   ],
   [
    18.2,
    90.15
   ],
   [
    18.47,
    89.25
   ],
   [
    26.93,
    80.6
   ],
   [
    28.89,
    78.29
   ],
   [
    28.89,
    77.88
   ],
   [
    26.92,
    75.6
   ],
   [
    26.5,
    75.46
   ],
   [
    26.15,
    75.57
   ],
   [
    23.23,
    78.86
   ],
   [
    14.89,
    87.37
   ],
   [
    14.43,
    87.5
   ],
   [
    13.36,
    86.78
   ],
   [
    12.8,
    86.83
   ],
   [
    6.85,
    92.7
   ],
   [
    5.32,
    92.7
   ],
   [
    4.45,
    93.15
   ],
   [
    3.71,
    92.71
   ],
   [
    2.41,
    92.71
   ],
   [
    1.52,
    93.15
   ],
   [
    0.82,
    92.7
   ],
   [
    0.39,
    92.63
   ],
   [
    -0.49,
    92.67
   ],
   [
    -1.22,
    93.0
   ],
   [
    -2.36,
    92.64
   ],
   [
    -3.0,
    92.63
   ],
   [
    -3.4,
    92.69
   ],
   [
    -4.09,
    93.12
   ],
   [
    -4.91,
    92.64
   ],
   [
    -6.31,
    92.56
   ],
   [
    -12.78,
    86.11
   ],
   [
    -13.36,
    86.06
   ],
   [
    -14.23,
    86.84
   ],
   [
    -14.58,
    86.82
   ],
   [
    -23.12,
    78.28
   ],
   [
    -26.32,
    74.7
   ],
   [
    -26.89,
    74.65
   ],
   [
    -27.59,
    75.18
   ],
   [
    -28.94,
    76.7
   ],
   [
    -29.14,
    77.11
   ],
   [
    -29.03,
    77.61
   ],
   [
    -22.59,
    84.34
   ],
   [
    -18.58,
    88.15
   ],
   [
    -18.26,
    88.81
   ],
   [
    -16.26,
    90.97
   ],
   [
    -16.26,
    91.23
   ],
   [
    -16.61,
    91.76
   ],
   [
    -16.51,
    92.12
   ],
   [
    -16.18,
    92.28
   ],
   [
    -15.62,
    92.13
   ],
   [
    -15.26,
    92.26
   ],
   [
    -13.07,
    94.61
   ],
   [
    -12.72,
    95.29
   ],
   [
    -7.25,
    100.8
   ],
   [
    -7.14,
    101.2
   ],
   [
    -7.39,
    101.67
   ],
   [
    -7.39,
    102.02
   ],
   [
    -6.73,
    103.01
   ]
  ],
  "polygon_area_check_m2": 435.17,
  "drawn": "Phase I design, fall 2000: 110 solid-outline geotextile bags (about 3.0 m x 2.2 m x 1.2 m each) in a V of two arms at 45 deg to the wave direction, with a 5 x 5 bag spine block at the apex. The 30 dashed 'optional' bags on the drawing are not part of the outline. This is NOT the final reef: Phase II (April 2001) put 90 more bags on top of these and widened the crest.",
  "geo": null,
  "y_range_m": [
   74.65,
   103.28
  ],
  "x_range_m": [
   -29.14,
   28.89
  ]
 },
 "seabed": {
  "kind": "alongshore-uniform cross-shore profile z(y); y from the MSL waterline",
  "extent": {
   "x": [
    -150,
    150
   ],
   "y": [
    -60.0,
    300.0
   ]
  },
  "profile_y_m": [
   -60.0,
   -55.0,
   -50.0,
   -45.0,
   -40.0,
   -35.0,
   -30.0,
   -25.0,
   -20.0,
   -15.0,
   -10.0,
   -5.0,
   0.0,
   5.0,
   10.0,
   15.0,
   20.0,
   25.0,
   30.0,
   35.0,
   40.0,
   45.0,
   50.0,
   55.0,
   60.0,
   65.0,
   70.0,
   75.0,
   80.0,
   85.0,
   90.0,
   95.0,
   100.0,
   105.0,
   110.0,
   115.0,
   120.0,
   125.0,
   130.0,
   135.0,
   140.0,
   145.0,
   150.0,
   155.0,
   160.0,
   165.0,
   170.0,
   175.0,
   180.0,
   185.0,
   190.0,
   195.0,
   200.0,
   205.0,
   210.0,
   215.0,
   220.0,
   225.0,
   230.0,
   235.0,
   240.0,
   245.0,
   250.0,
   255.0,
   260.0,
   265.0,
   270.0,
   275.0,
   280.0,
   285.0,
   290.0,
   295.0,
   300.0
  ],
  "profile_z_m": [
   3.763,
   3.563,
   3.329,
   3.077,
   2.855,
   2.644,
   2.426,
   2.195,
   1.932,
   1.633,
   1.259,
   0.711,
   0.0,
   -0.604,
   -0.985,
   -1.244,
   -1.406,
   -1.535,
   -1.653,
   -1.781,
   -1.931,
   -2.098,
   -2.274,
   -2.457,
   -2.64,
   -2.818,
   -2.986,
   -3.145,
   -3.303,
   -3.463,
   -3.622,
   -3.776,
   -3.927,
   -4.079,
   -4.23,
   -4.38,
   -4.526,
   -4.67,
   -4.813,
   -4.953,
   -5.091,
   -5.228,
   -5.364,
   -5.5,
   -5.635,
   -5.769,
   -5.901,
   -6.028,
   -6.151,
   -6.27,
   -6.388,
   -6.504,
   -6.623,
   -6.745,
   -6.871,
   -6.999,
   -7.13,
   -7.264,
   -7.397,
   -7.525,
   -7.647,
   -7.765,
   -7.876,
   -7.981,
   -8.08,
   -8.174,
   -8.261,
   -8.341,
   -8.414,
   -8.485,
   -8.554,
   -8.621,
   -8.687
  ],
  "profile_sd_m": [
   0.236,
   0.335,
   0.371,
   0.334,
   0.247,
   0.196,
   0.189,
   0.207,
   0.277,
   0.377,
   0.414,
   0.312,
   0.0,
   0.165,
   0.158,
   0.147,
   0.11,
   0.083,
   0.076,
   0.089,
   0.107,
   0.116,
   0.121,
   0.123,
   0.124,
   0.126,
   0.124,
   0.122,
   0.121,
   0.126,
   0.135,
   0.137,
   0.137,
   0.134,
   0.13,
   0.123,
   0.118,
   0.115,
   0.114,
   0.114,
   0.115,
   0.116,
   0.118,
   0.121,
   0.127,
   0.134,
   0.142,
   0.149,
   0.15,
   0.15,
   0.151,
   0.152,
   0.152,
   0.151,
   0.147,
   0.139,
   0.13,
   0.122,
   0.118,
   0.117,
   0.116,
   0.116,
   0.116,
   0.115,
   0.111,
   0.104,
   0.095,
   0.084,
   0.074,
   0.062,
   0.053,
   0.056,
   0.067
  ],
  "profile_zmin_m": [
   3.254,
   2.879,
   2.666,
   2.529,
   2.407,
   2.263,
   2.111,
   1.807,
   1.442,
   1.007,
   0.608,
   0.323,
   -0.0,
   -0.96,
   -1.305,
   -1.525,
   -1.611,
   -1.654,
   -1.769,
   -1.923,
   -2.093,
   -2.272,
   -2.457,
   -2.648,
   -2.835,
   -3.014,
   -3.17,
   -3.356,
   -3.551,
   -3.745,
   -3.94,
   -4.1,
   -4.247,
   -4.389,
   -4.531,
   -4.673,
   -4.814,
   -4.953,
   -5.095,
   -5.239,
   -5.381,
   -5.519,
   -5.657,
   -5.795,
   -5.933,
   -6.071,
   -6.214,
   -6.354,
   -6.483,
   -6.612,
   -6.741,
   -6.865,
   -6.99,
   -7.113,
   -7.226,
   -7.34,
   -7.454,
   -7.573,
   -7.697,
   -7.812,
   -7.91,
   -8.004,
   -8.095,
   -8.195,
   -8.291,
   -8.381,
   -8.446,
   -8.502,
   -8.546,
   -8.588,
   -8.637,
   -8.8,
   -8.96
  ],
  "profile_zmax_m": [
   4.145,
   3.961,
   3.804,
   3.655,
   3.354,
   3.032,
   2.714,
   2.633,
   2.437,
   2.247,
   2.261,
   1.725,
   0.0,
   -0.273,
   -0.563,
   -0.852,
   -1.111,
   -1.34,
   -1.452,
   -1.537,
   -1.631,
   -1.777,
   -1.928,
   -2.105,
   -2.284,
   -2.454,
   -2.618,
   -2.777,
   -2.935,
   -3.088,
   -3.238,
   -3.387,
   -3.545,
   -3.709,
   -3.873,
   -4.04,
   -4.204,
   -4.367,
   -4.525,
   -4.68,
   -4.823,
   -4.964,
   -5.108,
   -5.25,
   -5.388,
   -5.522,
   -5.654,
   -5.784,
   -5.897,
   -6.009,
   -6.117,
   -6.22,
   -6.332,
   -6.449,
   -6.59,
   -6.743,
   -6.9,
   -7.038,
   -7.171,
   -7.298,
   -7.43,
   -7.567,
   -7.698,
   -7.799,
   -7.884,
   -7.973,
   -8.07,
   -8.167,
   -8.264,
   -8.355,
   -8.439,
   -8.513,
   -8.58
  ],
  "crm_check_z_m": [
   4.024,
   3.763,
   3.451,
   3.089,
   2.682,
   2.238,
   1.785,
   1.359,
   0.989,
   0.675,
   0.411,
   0.189,
   0.0,
   -0.168,
   -0.331,
   -0.495,
   -0.663,
   -0.833,
   -1.005,
   -1.177,
   -1.345,
   -1.511,
   -1.674,
   -1.834,
   -1.99,
   -2.143,
   -2.295,
   -2.445,
   -2.593,
   -2.739,
   -2.884,
   -3.026,
   -3.168,
   -3.309,
   -3.448,
   -3.587,
   -3.724,
   -3.859,
   -3.993,
   -4.125,
   -4.256,
   -4.383,
   -4.509,
   -4.633,
   -4.756,
   -4.877,
   -4.999,
   -5.122,
   -5.248,
   -5.376,
   -5.507,
   -5.64,
   -5.774,
   -5.904,
   -6.031,
   -6.153,
   -6.267,
   -6.373,
   -6.471,
   -6.563,
   -6.649,
   -6.73,
   -6.807,
   -6.881,
   -6.953,
   -7.023,
   -7.092,
   -7.158,
   -7.22,
   -7.279,
   -7.336,
   -7.392,
   -7.444
  ],
  "navionics": {
   "y_m": [
    43.02,
    48.52,
    54.02,
    60.52,
    68.28,
    76.15,
    82.15,
    86.65,
    91.4,
    95.02,
    99.52,
    127.65,
    143.28,
    157.4,
    170.9,
    181.65,
    193.02,
    203.28,
    214.28,
    224.02,
    235.02,
    246.52,
    264.02,
    302.78
   ],
   "z_m": [
    -0.849,
    -1.154,
    -1.459,
    -1.763,
    -2.068,
    -2.373,
    -2.678,
    -2.983,
    -3.287,
    -3.592,
    -3.897,
    -4.202,
    -4.507,
    -4.811,
    -5.116,
    -5.421,
    -5.726,
    -6.031,
    -6.335,
    -6.64,
    -6.945,
    -7.25,
    -7.555,
    -7.859
   ],
   "profile_z_m": [
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    -0.959,
    -1.236,
    -1.505,
    -1.739,
    -1.939,
    -2.135,
    -2.328,
    -2.569,
    -2.871,
    -3.198,
    -3.591,
    -3.902,
    -3.956,
    -4.011,
    -4.065,
    -4.119,
    -4.173,
    -4.248,
    -4.345,
    -4.443,
    -4.544,
    -4.652,
    -4.76,
    -4.87,
    -4.983,
    -5.096,
    -5.232,
    -5.374,
    -5.511,
    -5.645,
    -5.785,
    -5.933,
    -6.078,
    -6.217,
    -6.358,
    -6.514,
    -6.667,
    -6.806,
    -6.944,
    -7.077,
    -7.21,
    -7.31,
    -7.397,
    -7.485,
    -7.562,
    -7.602,
    -7.641,
    -7.68,
    -7.72,
    -7.759,
    -7.798,
    -7.838
   ],
   "y_hint_m": 101.9,
   "valid_y_m": [
    43.0,
    302.8
   ],
   "layer": "Garmin Navionics SonarChart Maps (Marine Maps web viewer), depth units feet, zoom 18, 1 ft contours counted along 245 deg through 33.92058 N 118.43335 W",
   "datum_assumed": "MLLW (not stated by the app; test: RMS vs DEM 0.286 m MLLW, 0.318 m NAVD88, 0.539 m LAT, 1.021 m MSL)",
   "accessed": "2026-10-05",
   "n_contours": 24
  },
  "shoreline_y_m": 0.0,
  "nominal_reef_y_m": 91.44,
  "reef_offset_range_m": [
   60.0,
   130.0
  ],
  "datum": "z_MSL = z_NAVD88 - 0.792",
  "source": "NOAA NGDC (2010) Santa Monica CA 1/3 arc-second NAVD88 Coastal DEM; mean of 31 alongshore stations (+-150 m) about 33.92058 N 118.43335 W",
  "checks": {
   "dem_z_at_nominal_m": -3.67,
   "dem_sd_at_nominal_m": 0.14,
   "dem_z_at_tips_m": -3.13,
   "dem_z_at_apex_m": -4.03,
   "crm_z_at_nominal_m": -2.92,
   "y_at_15ft_m": 121.6,
   "slope_1_in": 32.0,
   "n_stations": 31,
   "waterline_offset_mean_m": -101.9,
   "waterline_offset_sd_m": 5.4,
   "navd88_to_msl_m": 0.792
  }
 },
 "reef": {
  "toe_polygon_xy_m": [
   [
    -6.28,
    103.27
   ],
   [
    -4.77,
    103.28
   ],
   [
    -4.25,
    102.98
   ],
   [
    -3.53,
    103.28
   ],
   [
    -2.02,
    103.28
   ],
   [
    -1.38,
    102.96
   ],
   [
    -0.66,
    103.27
   ],
   [
    0.86,
    103.26
   ],
   [
    1.51,
    102.84
   ],
   [
    2.14,
    103.25
   ],
   [
    3.84,
    103.23
   ],
   [
    4.42,
    102.84
   ],
   [
    5.0,
    103.22
   ],
   [
    6.76,
    103.21
   ],
   [
    7.82,
    102.42
   ],
   [
    8.49,
    102.48
   ],
   [
    8.6,
    102.16
   ],
   [
    7.98,
    101.31
   ],
   [
    8.04,
    100.85
   ],
   [
    18.2,
    90.15
   ],
   [
    18.47,
    89.25
   ],
   [
    26.93,
    80.6
   ],
   [
    28.89,
    78.29
   ],
   [
    28.89,
    77.88
   ],
   [
    26.92,
    75.6
   ],
   [
    26.5,
    75.46
   ],
   [
    26.15,
    75.57
   ],
   [
    23.23,
    78.86
   ],
   [
    14.89,
    87.37
   ],
   [
    14.43,
    87.5
   ],
   [
    13.36,
    86.78
   ],
   [
    12.8,
    86.83
   ],
   [
    6.85,
    92.7
   ],
   [
    5.32,
    92.7
   ],
   [
    4.45,
    93.15
   ],
   [
    3.71,
    92.71
   ],
   [
    2.41,
    92.71
   ],
   [
    1.52,
    93.15
   ],
   [
    0.82,
    92.7
   ],
   [
    0.39,
    92.63
   ],
   [
    -0.49,
    92.67
   ],
   [
    -1.22,
    93.0
   ],
   [
    -2.36,
    92.64
   ],
   [
    -3.0,
    92.63
   ],
   [
    -3.4,
    92.69
   ],
   [
    -4.09,
    93.12
   ],
   [
    -4.91,
    92.64
   ],
   [
    -6.31,
    92.56
   ],
   [
    -12.78,
    86.11
   ],
   [
    -13.36,
    86.06
   ],
   [
    -14.23,
    86.84
   ],
   [
    -14.58,
    86.82
   ],
   [
    -23.12,
    78.28
   ],
   [
    -26.32,
    74.7
   ],
   [
    -26.89,
    74.65
   ],
   [
    -27.59,
    75.18
   ],
   [
    -28.94,
    76.7
   ],
   [
    -29.14,
    77.11
   ],
   [
    -29.03,
    77.61
   ],
   [
    -22.59,
    84.34
   ],
   [
    -18.58,
    88.15
   ],
   [
    -18.26,
    88.81
   ],
   [
    -16.26,
    90.97
   ],
   [
    -16.26,
    91.23
   ],
   [
    -16.61,
    91.76
   ],
   [
    -16.51,
    92.12
   ],
   [
    -16.18,
    92.28
   ],
   [
    -15.62,
    92.13
   ],
   [
    -15.26,
    92.26
   ],
   [
    -13.07,
    94.61
   ],
   [
    -12.72,
    95.29
   ],
   [
    -7.25,
    100.8
   ],
   [
    -7.14,
    101.2
   ],
   [
    -7.39,
    101.67
   ],
   [
    -7.39,
    102.02
   ],
   [
    -6.73,
    103.01
   ]
  ],
  "states": [
   {
    "id": "B",
    "mode": "thickness",
    "label": "B  Phase I as installed (Sept 2000): outermost point approximately 6 ft below MLLW (Borrero & Nelsen 2003 p.2); top follows the seabed",
    "short": "B: as installed (6 ft MLLW), top parallel to bed",
    "z_ref_msl": -2.678,
    "y_ref_m": 103.28,
    "datum_stated": "MLLW",
    "value_stated": "approximately - 6 ft MLLW (= 1.829 m; ICCE 2010: 1.8 m)",
    "source_id": "S10 Borrero & Nelsen 2003 p.2 (primary; ICCE 2010 S2 repeats it as 1.8 m)",
    "applies": "the outermost point (offshore face of the V apex block); carried along the reef at constant thickness above the bed (assumption A4)",
    "uncertainty_m": 0.3,
    "note": "The only as-built number found. Thickness = z_ref - seabed(apex) (>= one 1.2 m bag course).",
    "thickness_m": 1.349,
    "volume_m3": 443.0,
    "h_max_m": 1.35,
    "h_mean_m": 1.02,
    "plateau_area_m2": 223.4,
    "crest_h_apex_m": 1.35,
    "crest_h_tips_m": 1.35,
    "top_z_apex_msl_m": -2.678,
    "top_z_tips_msl_m": -1.784,
    "top_apex_below_mllw_m": 1.83,
    "top_tips_below_mllw_m": 0.94,
    "top_apex_below_lat_m": 1.21,
    "top_tips_below_lat_m": 0.32,
    "courses_apex": 1.12,
    "depth_below_msl_m": 2.678,
    "depth_below_mllw_m": 1.829,
    "depth_below_lat_m": 1.209
   },
   {
    "id": "A",
    "mode": "level",
    "label": "A  Phase I design: top of bag min depth -6 ft MSL (Skelly drawing), level crest",
    "short": "A: design level, -6 ft MSL",
    "z_msl": -1.829,
    "datum_stated": "MSL",
    "value_stated": "-6 ft MSL",
    "source_id": "P1/img1 Skelly Engineering drawing, call-outs at both arm tips",
    "applies": "design minimum depth of the bag tops (not a survey); level crest assumed wherever the stack can reach it",
    "uncertainty_m": 0.15,
    "note": "The drawing prints the SAME number (6 ft) with the datum label MSL; the paper prints '- 6 ft MLLW' for the as-installed outermost point. A and B differ by exactly MSL - MLLW (0.85 m): one number, two datum labels. Which label is right is not stated anywhere; A is also close to the Phase II crest (-1.76 m MSL).",
    "volume_m3": 550.0,
    "h_max_m": 2.13,
    "h_mean_m": 1.27,
    "plateau_area_m2": 161.2,
    "crest_h_apex_m": 2.2,
    "crest_h_tips_m": 1.3,
    "top_z_apex_msl_m": -1.829,
    "top_z_tips_msl_m": -1.829,
    "top_apex_below_mllw_m": 0.98,
    "top_tips_below_mllw_m": 0.98,
    "top_apex_below_lat_m": 0.36,
    "top_tips_below_lat_m": 0.36,
    "courses_apex": 1.83,
    "depth_below_msl_m": 1.829,
    "depth_below_mllw_m": 0.98,
    "depth_below_lat_m": 0.36
   }
  ],
  "not_modelled": [
   {
    "id": "C",
    "label": "C  After Phase II (23-24 April 2001, +90 bags placed over Phase I; crest widened and made shallower): 'within 3 ft of MLLW'",
    "z_msl": -1.763,
    "value_stated": "within 3 ft (0.914 m) of MLLW (ICCE 2010: 1 m; RWR: 0.9 m)",
    "source_id": "S10 Borrero & Nelsen 2003 p.3 (primary); S2; S3",
    "reason": "later change of the structure (not the as-built Phase I); plan extent after widening not drawn anywhere",
    "depth_below_mllw_m": 0.914,
    "depth_below_lat_m": 0.294
   },
   {
    "id": "R7",
    "label": "Surfline 2008 comment ('8 feet deep at zero tide')",
    "z_msl": -3.29,
    "value_stated": "8 ft at zero tide (if zero tide = MLLW)",
    "source_id": "card R7 (Cloudflare, not re-fetched)",
    "reason": "anonymous comment, datum and date unclear; shown only as the deep bound of the crest-depth range",
    "depth_below_mllw_m": 2.441,
    "depth_below_lat_m": 1.821
   }
  ],
  "default_state": "B",
  "bag": {
   "length_m": 3.0,
   "width_m": 2.13,
   "height_m": 1.2,
   "volume_max_m3": 7.9,
   "fill_min": 0.8,
   "fill_max": 0.9
  },
  "slope_run_default": 1.0,
  "slope_run_range": [
   0.5,
   2.5
  ],
  "min_height_m": 1.2,
  "y_apex_m": 103.28,
  "y_tips_m": 74.65,
  "rule": "h(x,y) = max(0, min(h_top, d_in(x,y) / slope_run)); h_top = z_c - z_seabed(y) (state A, level crest) or z_ref - z_seabed(y_apex) (state B, constant thickness); both >= min_height; d_in = distance inside the toe outline; surface z = z_seabed + h",
  "offshore_presets": [
   {
    "label": "text: 100 yd from the waterline",
    "y": 91.44
   },
   {
    "label": "hint 33.92058 N, 118.43335 W",
    "y": 101.9
   },
   {
    "label": "CCC '15 ft (MSL)' depth",
    "y": 121.6
   }
  ],
  "volume_check": {
   "model_volume_by_state_slope_m3": {
    "B": {
     "0.5": 514.0,
     "0.75": 478.0,
     "1.0": 443.0,
     "1.5": 374.0,
     "2.0": 316.0
    },
    "A": {
     "0.5": 672.0,
     "0.75": 611.0,
     "1.0": 550.0,
     "1.5": 435.0,
     "2.0": 344.0
    }
   },
   "bags_110_80_90pct_m3": [
    695,
    782
   ],
   "bags_110_max_m3": 869,
   "bags_200_80_90pct_m3": [
    1264,
    1422
   ],
   "stated_final_volume_m3": [
    1400,
    1600
   ]
  },
  "sensitivity_seabed_position": {
   "-25": {
    "seabed_z_m": -2.87,
    "thickness_B_m": 1.2,
    "crest_height_A_m": 1.04
   },
   "0": {
    "seabed_z_m": -3.67,
    "thickness_B_m": 1.35,
    "crest_height_A_m": 1.84
   },
   "25": {
    "seabed_z_m": -4.42,
    "thickness_B_m": 2.09,
    "crest_height_A_m": 2.59
   },
   "40": {
    "seabed_z_m": -4.85,
    "thickness_B_m": 2.5,
    "crest_height_A_m": 3.02
   }
  },
  "uncertainty": {
   "sig_zc_m": 0.3,
   "sig_zb_m": 0.8,
   "sig_H_m": 0.85,
   "sd_estimates_m": 0.83,
   "sig_pos_m": 0.78,
   "sig_y_m": 25.0,
   "estimates": {
    "NOAA DEM at y = 91.44 m": -3.67,
    "NOAA CRM 1 arc-sec at y = 91.44 m": -2.92,
    "CCC 1998 text '15 feet (MSL)'": -4.57,
    "RWR text 'about 5 m deep' (datum not stated)": -5.0,
    "B&N 2003 Fig. 5: beds either side of the reef, Oct 2001 (axis read as MLLW)": -3.73,
    "Navionics SonarChart 91.44 m from the chart coastline (MLLW assumed)": -3.02
   }
  }
 },
 "water": {
  "levels": [
   {
    "id": "LAT",
    "z": -1.469,
    "label": "LAT (lowest astronomical tide)",
    "source": "NOAA CO-OPS 9410840 Santa Monica, epoch 1983-2001 (LAT/HAT: station record, HAT predicted 2040-07-24)"
   },
   {
    "id": "MLLW",
    "z": -0.849,
    "label": "MLLW (mean lower low water)",
    "source": "NOAA CO-OPS 9410840 Santa Monica, epoch 1983-2001 (LAT/HAT: station record, HAT predicted 2040-07-24)"
   },
   {
    "id": "MLW",
    "z": -0.566,
    "label": "MLW",
    "source": "NOAA CO-OPS 9410840 Santa Monica, epoch 1983-2001 (LAT/HAT: station record, HAT predicted 2040-07-24)"
   },
   {
    "id": "MSL",
    "z": 0.0,
    "label": "MSL (mean sea level) = model zero",
    "source": "NOAA CO-OPS 9410840 Santa Monica, epoch 1983-2001 (LAT/HAT: station record, HAT predicted 2040-07-24)"
   },
   {
    "id": "MHW",
    "z": 0.579,
    "label": "MHW",
    "source": "NOAA CO-OPS 9410840 Santa Monica, epoch 1983-2001 (LAT/HAT: station record, HAT predicted 2040-07-24)"
   },
   {
    "id": "MHHW",
    "z": 0.804,
    "label": "MHHW (mean higher high water)",
    "source": "NOAA CO-OPS 9410840 Santa Monica, epoch 1983-2001 (LAT/HAT: station record, HAT predicted 2040-07-24)"
   },
   {
    "id": "HAT",
    "z": 1.382,
    "label": "HAT (highest astronomical tide)",
    "source": "NOAA CO-OPS 9410840 Santa Monica, epoch 1983-2001 (LAT/HAT: station record, HAT predicted 2040-07-24)"
   }
  ],
  "default": "MSL",
  "datum_note": "z in m above MSL; MSL - MLLW = 0.849 m (LA Outer Harbor 0.861)"
 },
 "shoreline": {
  "y_m": 0.0,
  "definition": "MSL waterline (z = 0 contour of the seabed profile)"
 },
 "north": {
  "xy": [
   -0.9063,
   -0.4226
  ],
  "bearing_deg": 0
 },
 "position_hint": {
  "lat": 33.92058,
  "lon": -118.43335,
  "uncertainty_m": 100,
  "utm11n": [
   367505.0,
   3754275.0
  ],
  "note": "inferred: centre of the Borrero & Nelsen (2003) Fig. 9 survey window, consistent with 'about 200 m south of the 1-mile outfall'; shape.json geo = null (no georeferenced outline)",
  "superseded_text_hint": {
   "lat": 33.9188,
   "lon": -118.4324,
   "basis": "CCC 1998: 300 yd north of the Grand Avenue jetty, 100 yd offshore",
   "distance_to_new_hint_m": 217
  }
 },
 "provenance": [
  {
   "parameter": "plan outline (toe polygon)",
   "value": "76 vertices, 435.2 m2, 58.0 x 28.6 m",
   "unit": "m",
   "source_id": "P1 shape.json (img1 Skelly drawing)",
   "method": "outline of the solid-outline bags traced on the scaled design drawing (scale bar 0-90 ft), canonical frame of shape.json",
   "uncertainty": "+-0.2 m on the outline (+-4 % area); scale bar +-3-5 %",
   "estimated": false
  },
  {
   "parameter": "state modelled",
   "value": "Phase I as built, Sept 2000: footprint = Skelly design layout (110 solid bags), top = ICCE as-installed depth",
   "unit": "-",
   "source_id": "P1 / S2 / VERIFY.md check 2",
   "method": "no as-built plan exists; Phase II (Apr 2001) and the removal (fall 2008 / fall 2010) are in the caption only, not modelled",
   "uncertainty": "design vs real structure differ by metres (bags moved, sank, buried)",
   "estimated": false
  },
  {
   "parameter": "frame orientation",
   "value": "+x toward 155 deg, +y (offshore) toward 245 deg",
   "unit": "deg",
   "source_id": "P1 shape.json angles; img4 shoreline fit; img6 north arrow",
   "method": "present shoreline fitted on Esri 2026-01-09 image (155.5 deg); concept plan bisector 61 deg; SonarChart 0 ft line trend gives 158 deg",
   "uncertainty": "+-5 deg (drawing has no north arrow)",
   "estimated": true
  },
  {
   "parameter": "position (lat/lon)",
   "value": "33.92058 N, 118.43335 W (inferred hint; not surveyed)",
   "unit": "deg",
   "source_id": "S10 Borrero & Nelsen 2003 Fig. 9 (UTM window) + p.1 text + Fig. 2; Navionics outfall landfall",
   "method": "centre of the Fig. 9 survey window (UTM 11N 367505 E, 3754275 N); agrees to <= 35 m with 'about 200 m south of the 1-mile outfall' (outfall landfall read on the Navionics chart) + 91 m offshore; Fig. 2 scale gives 320 m instead of 200 m; the earlier text hint (CCC 1998: 300 yd north of the Grand Avenue jetty, 33.9188 N 118.4324 W) is 217 m away and superseded",
   "uncertainty": "+-100 m alongshore (window half-length 56 m; outfall- and jetty-based estimates span 190 m); no effect on depths (bed uniform alongshore)",
   "estimated": true
  },
  {
   "parameter": "crest B: top of the reef at the offshore face, Phase I as installed (MODELLED, default)",
   "value": "-2.678 (stated approximately - 6 ft MLLW (= 1.829 m; ICCE 2010: 1.8 m))",
   "unit": "m rel. MSL",
   "source_id": "S10 Borrero & Nelsen 2003 p.2 (primary; ICCE 2010 S2 repeats it as 1.8 m)",
   "method": "z_MSL = -(6 ft x 0.3048 + (MSL - MLLW)) = -(1.829 + 0.849); carried along the reef at constant thickness 1.35 m above the DEM seabed",
   "uncertainty": "+-0.30 m (reading 'approximately', single point, as-built variation); datum MLLW now confirmed in the primary paper",
   "estimated": false
  },
  {
   "parameter": "crest A: design minimum depth of the bag tops (MODELLED alternative)",
   "value": "-1.829 (stated -6 ft MSL)",
   "unit": "m rel. MSL",
   "source_id": "P1/img1 call-outs at both arm tips",
   "method": "6 ft x 0.3048 m/ft; datum label MSL as printed (the paper prints the same 6 ft as MLLW); level crest",
   "uncertainty": "+-0.15 m (foot rounding); 0.85 m above crest B = MSL - MLLW",
   "estimated": false
  },
  {
   "parameter": "crest C: after Phase II (NOT modelled)",
   "value": "-1.763 (stated within 3 ft (0.914 m) of MLLW (ICCE 2010: 1 m; RWR: 0.9 m))",
   "unit": "m rel. MSL",
   "source_id": "S10 Borrero & Nelsen 2003 p.3 (primary); S2; S3",
   "method": "z_MSL = -(3 ft x 0.3048 + 0.849); Fig. 8 gives the May 2001 crest as -1.77 m on its axis (datum not stated) and 1.5 m of erosion by Sept 2002",
   "uncertainty": "later change: shown for the record only",
   "estimated": false
  },
  {
   "parameter": "reef after Phase II (NOT modelled): centreline relief and width",
   "value": "relief 2.1 m above the beds, base width 29 m, crest 88.7 m from the z = 0 crossing (Oct 2001)",
   "unit": "m",
   "source_id": "S10 Borrero & Nelsen 2003 Figs 5, 7, 8 (profile along range line 3, vector paths digitised)",
   "method": "bn_digitise.py: peak minus the lowest vertex landward and seaward of the peak; the design apex block is only 10.6 m wide at the centreline",
   "uncertainty": "+-0.2 m vertical; axis datum not stated (Fig. 7/8 = Fig. 5 + 1.44 m)",
   "estimated": false
  },
  {
   "parameter": "bag size",
   "value": "4 x 7 x 10 ft = 1.2 x 2.1 x 3.0 m, maximum 280 ft3 = 7.9 m3, filled 80-90 %, about 14 t",
   "unit": "m",
   "source_id": "S10 Borrero & Nelsen 2003 p.2 (primary); S2 ICCE 2010 Fig.1 & p.7",
   "method": "stated in the paper; 3.0 x 2.13 x 1.2 m rectangular = 7.67 m3 (3 % below the stated maximum); consistent with the drawing grid pitch 6.9 x 9.5 ft",
   "uncertainty": "+-3 % (bag shape)",
   "estimated": false
  },
  {
   "parameter": "bag counts and dates",
   "value": "Phase I: 110 bags, installed 22 Sept 2000; Phase II: 90 bags, 23-24 April 2001 (+80 % volume); total 200 bags, 'approximately 1600 m3'",
   "unit": "-",
   "source_id": "S10 Borrero & Nelsen 2003 pp.2-3, 16",
   "method": "1600 m3 = 200 x 7.9 m3 (NOMINAL volume, not the 80-90 % filled volume); 90/110 = 0.82 vs '+80 %'",
   "uncertainty": "stated; stack height / number of courses NOT stated",
   "estimated": false
  },
  {
   "parameter": "side slope of the bag stack",
   "value": "1.0 H : 1 V (range 0.5-2.5)",
   "unit": "-",
   "source_id": "none (assumption A5)",
   "method": "bag edge of a 1.2-1.5 m course; volume sensitivity in METHODS_3D.md section 5",
   "uncertainty": "0.5-2.5",
   "estimated": true
  },
  {
   "parameter": "reef thickness (state B)",
   "value": "1.35 m = 1.12 bag courses (apex), 1.35 m at the tips",
   "unit": "m",
   "source_id": "derived: crest B minus DEM seabed at the apex",
   "method": "thickness = z_B - z_seabed(y_apex), applied as a constant over the reef (top parallel to the bed)",
   "uncertainty": "+-0.8 m (propagation of crest and seabed uncertainty)",
   "estimated": true
  },
  {
   "parameter": "seabed profile (primary)",
   "value": "z(91.4 m) = -3.67 m MSL, slope 1:32 over the reef",
   "unit": "m rel. MSL",
   "source_id": "S5 NOAA NGDC Santa Monica 1/3 arc-sec NAVD88 DEM (2010)",
   "method": "mean of 31 alongshore profiles, each aligned on its MSL waterline; z_MSL = z_NAVD88 - 0.792",
   "uncertainty": "+-0.8 m (SD of 6 independent depth estimates 0.83 m; position +-25 m x slope = 0.78 m; alongshore sd 0.14 m)",
   "estimated": false
  },
  {
   "parameter": "seabed profile (independent check, selectable in the viewer)",
   "value": "z(hint) = -3.92 m MSL (10.1 ft below chart datum); DEM -3.99 m",
   "unit": "m rel. MSL",
   "source_id": "S7 Garmin Navionics SonarChart (Marine Maps web viewer), accessed 2026-10-05",
   "method": "24 1 ft contours counted along 245 deg through the hint (nav_annotate.py); chart datum assumed MLLW: z_MSL = -(n x 0.3048) - 0.849; seabed only (reef removed)",
   "uncertainty": "+-0.3 m in the reef zone (mean diff to DEM +0.29 m, max 0.55 m); datum assumed; +-1 ft counting error",
   "estimated": true
  },
  {
   "parameter": "reef distance from the MSL waterline",
   "value": "91.44 m (centroid)",
   "unit": "m",
   "source_id": "P1 (text: 100 yd offshore, CCC E-98-15 p.11; Wikipedia; RWR 'roughly 100 meters')",
   "method": "text value; the waterline is the MSL contour of the DEM; hint-based position gives 101.9 m; B&N 2003 Fig. 5 (axis read as MLLW, MSL = +0.849 m) puts the Oct 2001 crest 72.3 m and the centre of the base 83.8 m from the MSL line (Fig. 7 axis read as MSL: 88.7 / 94.3 m)",
   "uncertainty": "+-25 m (-> +-0.8 m seabed depth)",
   "estimated": true
  },
  {
   "parameter": "shoreline",
   "value": "y = 0 at the MSL waterline",
   "unit": "m",
   "source_id": "S5 DEM",
   "method": "z_MSL = 0 contour of the seabed profile; beach face 1:10 to 1:30",
   "uncertainty": "+-10 m (alongshore sd of waterline 5.4 m, seasonal berm changes; the Navionics 0 ft line lies 40 m seaward of the DEM's MLLW line)",
   "estimated": false
  },
  {
   "parameter": "tidal datum LAT",
   "value": "-1.469",
   "unit": "m rel. MSL",
   "source_id": "S4 NOAA CO-OPS 9410840 (epoch 1983-2001)",
   "method": "station-datum value minus MSL (1.594 m)",
   "uncertainty": "+-0.03 m transfer to El Segundo (12.5 km); LA Outer Harbor MSL-MLLW differs by 0.012 m",
   "estimated": false
  },
  {
   "parameter": "tidal datum MLLW",
   "value": "-0.849",
   "unit": "m rel. MSL",
   "source_id": "S4 NOAA CO-OPS 9410840 (epoch 1983-2001)",
   "method": "station-datum value minus MSL (1.594 m)",
   "uncertainty": "+-0.03 m transfer to El Segundo (12.5 km); LA Outer Harbor MSL-MLLW differs by 0.012 m",
   "estimated": false
  },
  {
   "parameter": "tidal datum MLW",
   "value": "-0.566",
   "unit": "m rel. MSL",
   "source_id": "S4 NOAA CO-OPS 9410840 (epoch 1983-2001)",
   "method": "station-datum value minus MSL (1.594 m)",
   "uncertainty": "+-0.03 m transfer to El Segundo (12.5 km); LA Outer Harbor MSL-MLLW differs by 0.012 m",
   "estimated": false
  },
  {
   "parameter": "tidal datum MSL",
   "value": "+0.000",
   "unit": "m rel. MSL",
   "source_id": "S4 NOAA CO-OPS 9410840 (epoch 1983-2001)",
   "method": "station-datum value minus MSL (1.594 m)",
   "uncertainty": "+-0.03 m transfer to El Segundo (12.5 km); LA Outer Harbor MSL-MLLW differs by 0.012 m",
   "estimated": false
  },
  {
   "parameter": "tidal datum MHW",
   "value": "+0.579",
   "unit": "m rel. MSL",
   "source_id": "S4 NOAA CO-OPS 9410840 (epoch 1983-2001)",
   "method": "station-datum value minus MSL (1.594 m)",
   "uncertainty": "+-0.03 m transfer to El Segundo (12.5 km); LA Outer Harbor MSL-MLLW differs by 0.012 m",
   "estimated": false
  },
  {
   "parameter": "tidal datum MHHW",
   "value": "+0.804",
   "unit": "m rel. MSL",
   "source_id": "S4 NOAA CO-OPS 9410840 (epoch 1983-2001)",
   "method": "station-datum value minus MSL (1.594 m)",
   "uncertainty": "+-0.03 m transfer to El Segundo (12.5 km); LA Outer Harbor MSL-MLLW differs by 0.012 m",
   "estimated": false
  },
  {
   "parameter": "tidal datum HAT",
   "value": "+1.382",
   "unit": "m rel. MSL",
   "source_id": "S4 NOAA CO-OPS 9410840 (epoch 1983-2001)",
   "method": "station-datum value minus MSL (1.594 m)",
   "uncertainty": "+-0.03 m transfer to El Segundo (12.5 km); LA Outer Harbor MSL-MLLW differs by 0.012 m",
   "estimated": false
  },
  {
   "parameter": "north direction",
   "value": "(-0.906, -0.423) in (x, y)",
   "unit": "-",
   "source_id": "P1 frame",
   "method": "bearing 0 deg = x-bearing 155 deg rotated by -155 deg",
   "uncertainty": "+-5 deg",
   "estimated": true
  }
 ],
 "sources": [
  {
   "id": "P1",
   "citation": "shape.json of this reef (07_scale/shapes/prattes-reef-el-segundo/shape.json), traced on img1 = Skelly Engineering (c. 2000) plan drawing 'PRATTE'S REEF' via Raised Water Research; verified 2026-10-04",
   "url": "https://raisedwaterresearch.com/wp-content/uploads/2019/07/Pratts-Reef-Diagram.png"
  },
  {
   "id": "S1",
   "citation": "California Coastal Commission (1998). Staff report W5a, application E-98-15 (Surfrider Foundation - Pratte's Reef), hearing 13 Oct 1998; Exhibits 2 and 3 by Skelly Engineering (1997, 1996)",
   "url": "https://documents.coastal.ca.gov/reports/1998/10/W5a-10-1998.pdf"
  },
  {
   "id": "S2",
   "citation": "Borrero, J.C., Mead, S.T. & Moores, A. (2010). Stability considerations and case studies of submerged structures constructed from large, sand filled, geotextile containers. Coastal Engineering Proceedings 1(32), structures.60",
   "url": "https://doi.org/10.9753/icce.v32.structures.60"
  },
  {
   "id": "S3",
   "citation": "Raised Water Research (n.d.). Pratte's Reef. accessed 2026-10-05",
   "url": "https://raisedwaterresearch.com/spot/artificial-reef/us/california/prattes-reef/"
  },
  {
   "id": "S4",
   "citation": "NOAA CO-OPS (2026). Tidal datums, station 9410840 Santa Monica, CA, epoch 1983-2001 (cross-check 9410660 Los Angeles)",
   "url": "https://api.tidesandcurrents.noaa.gov/mdapi/prod/webapi/stations/9410840/datums.json?units=metric"
  },
  {
   "id": "S5",
   "citation": "NOAA National Geophysical Data Center (2010). Santa Monica, California 1/3 arc-second NAVD 88 Coastal Digital Elevation Model",
   "url": "https://www.ngdc.noaa.gov/metaview/page?xml=NOAA/NESDIS/NGDC/MGG/DEM/iso/xml/726.xml&view=getDataView&header=none"
  },
  {
   "id": "S6",
   "citation": "NOAA National Geophysical Data Center (2012/2013). U.S. Coastal Relief Model - Southern California v2 (1 arc-second), doi:10.7289/V5V985ZM",
   "url": "https://www.ngdc.noaa.gov/metaview/page?xml=NOAA/NESDIS/NGDC/MGG/DEM/iso/xml/4970.xml&view=getDataView&header=none"
  },
  {
   "id": "S7",
   "citation": "Garmin Navionics (2026). Marine Maps web viewer (SonarChart Maps and Nautical Charts layers), reached via webapp.navionics.com; accessed 2026-10-05; screenshots private research copies, not for navigation",
   "url": "https://maps.garmin.com/en-US/marine/"
  },
  {
   "id": "S8",
   "citation": "NOAA CO-OPS (2026). Tidal datums, station 9410660 Los Angeles Outer Harbor, CA, epoch 1983-2001 (cross-check of MSL-MLLW)",
   "url": "https://api.tidesandcurrents.noaa.gov/mdapi/prod/webapi/stations/9410660/datums.json?units=metric"
  },
  {
   "id": "S10",
   "citation": "Borrero, J.C. & Nelsen, C. (2003). Results of a comprehensive monitoring program at Pratte's Reef. In: Black, K. & Mead, S. (eds), Proceedings of the 3rd International Surfing Reef Symposium, Raglan, New Zealand (venue and year as cited in R23; the 16-page PDF supplied by Lior on 2026-10-05 prints neither). Private research copy.",
   "url": "src/borrero_nelsen_2003_prattes_monitoring_results.pdf (local copy; original URL unknown)"
  },
  {
   "id": "S9",
   "citation": "Reef card 02_research/reefs/prattes-reef-el-segundo.json (verified 2026-09-25): removal dates (Phase I removal 30 Sept-17 Oct 2008, remaining bags fall 2010) from Surfrider Foundation news, Coastal Frontiers Corp. case study and Surfline (2008); not re-fetched in this run",
   "url": "https://www.coastalfrontiers.com/removal-of-prattes-reef"
  }
 ],
 "confidence_3d": {
  "level": "low",
  "reason": "Every input has a source, and the 2003 monitoring paper now confirms the datum of the as-installed crest (about 6 ft below MLLW), the bag size, the dates and, through a georeferenced survey window, the position to about +-100 m; the tide datums and the seabed (NOAA DEM and Navionics agree within 0.3 m in the reef zone) are well supported. But there is still no as-built plan (the paper's Fig. 4 is the design layout), the stack height is not stated and the single-course model holds only 443 m3 against 695-782 m3 for 110 bags, the Phase I crest is one point that differs by 0.8 m from the design reading, and the vertical uncertainty (+-0.85 m) is more than half the reef height (1.4 m).",
  "reason_short": "LOW: all inputs sourced and the 2003 paper fixes datum, bag size, dates and position (+-100 m), but no as-built plan, stack height unknown (volume gap 252-339 m3), crest readings differ by 0.8 m; vertical error (+-0.85 m) is over half the 1.4 m reef height."
 },
 "inputs_status": {
  "plan": "sourced - verified outline of the Phase I design layout (435.2 m2, 58.0 x 28.6 m); the 2003 paper's Fig. 4 is the same design drawing, so no as-built plan exists",
  "crest": "sourced - Phase I outermost point approximately 6 ft below MLLW (Borrero & Nelsen 2003 p.2; datum MLLW now confirmed) = -2.68 m MSL, default; Skelly design minimum -6 ft MSL = -1.83 m MSL (same number, other datum label) as alternative; variation along the crest assumed",
  "height_slopes": "estimated - bag size 4 x 7 x 10 ft now primary; number of courses NOT stated by any source; one course (thickness 1.35 m from crest B minus the DEM seabed) assumed; side slope 1H:1V assumed; the 110-bag volume check fails (443 vs 695-782 m3)",
  "seabed": "sourced - NOAA 1/3 arc-sec DEM (primary), Navionics SonarChart (check) and the 2003 paper's profiles (beds beside the reef -3.73 m MSL if the axis is MLLW): DEM -3.99 vs Navionics -3.92 m MSL at the hint; reef distance +-25 m -> +-0.8 m",
  "position": "inferred - Borrero & Nelsen (2003) Fig. 9 survey window centre 33.92058 N, 118.43335 W, consistent with '200 m south of the 1-mile outfall'; +-100 m; not surveyed, no georeferenced outline",
  "tides": "sourced - NOAA CO-OPS 9410840 Santa Monica (cross-check 9410660); MSL-MLLW = 0.849 m"
 },
 "stats": {
  "B": {
   "volume_m3": 443.0,
   "h_max_m": 1.35,
   "h_mean_m": 1.02,
   "plateau_area_m2": 223.4,
   "crest_h_apex_m": 1.35,
   "crest_h_tips_m": 1.35,
   "top_z_apex_msl_m": -2.678,
   "top_z_tips_msl_m": -1.784,
   "top_apex_below_mllw_m": 1.83,
   "top_tips_below_mllw_m": 0.94,
   "top_apex_below_lat_m": 1.21,
   "top_tips_below_lat_m": 0.32,
   "courses_apex": 1.12
  },
  "A": {
   "volume_m3": 550.0,
   "h_max_m": 2.13,
   "h_mean_m": 1.27,
   "plateau_area_m2": 161.2,
   "crest_h_apex_m": 2.2,
   "crest_h_tips_m": 1.3,
   "top_z_apex_msl_m": -1.829,
   "top_z_tips_msl_m": -1.829,
   "top_apex_below_mllw_m": 0.98,
   "top_tips_below_mllw_m": 0.98,
   "top_apex_below_lat_m": 0.36,
   "top_tips_below_lat_m": 0.36,
   "courses_apex": 1.83
  }
 }
};
