"""mmr_text.py - sources, provenance rows, confidence and input statuses of the Mount Maunganui model (called by build_3d.py)."""

VER_IDS = ['multibeam_2013_m2p0', 'asr_installed_toe_2008']


def add_text(model, comp, nav):
    c_def = comp['versions'][VER_IDS[0]]; c_toe = comp['versions'][VER_IDS[1]]
    v_s = c_def['volume_by_bed']['-4.0']['volume_m3']; v_t = c_toe['volume_by_bed']['-4.0']['volume_m3']
    zr = round(nav['z_cd_at_reef_centroid'], 2)
    BOPRC = 'https://www.boprc.govt.nz/media/558385/mount-maunganui-reef-assessment-of-management-options.pdf'
    model['sources'] = [
        {'id': 'img1', 'short': 'BoPRC Fig 3, 18 Jul 2013 multibeam plan', 'citation': 'Focus Resource Management Group (2013/14). Mount Maunganui Reef - Assessment of Management Options, Figure 3 (survey 18 July 2013, University of Waikato & Discovery Marine Ltd). Bay of Plenty Regional Council. Registry mount-maunganui-reef-img-08.', 'url': BOPRC},
        {'id': 'ctx9', 'short': 'BoPRC Fig 5, colour DEM 2013', 'citation': 'Same report, Figure 5 (hillshaded colour-coded DEM of the July 2013 survey with its own NZ-grid ticks and colour bar). Registry mount-maunganui-reef-img-04.', 'url': BOPRC},
        {'id': 'img3', 'short': 'ASR "Mount Reef Installed" bathymetry (2008)', 'citation': 'ASR Ltd / Raised Water Research. "Mount Reef Installed" - colour-coded bathymetry of the completed reef (legend -1.8 to -7.4 m, datum not stated; undated, after Aug 2008). Registry mount-maunganui-reef-img-10.', 'url': 'https://raisedwaterresearch.com/wp-content/uploads/2019/11/Mount-Reef-Installed.jpg'},
        {'id': 'img2', 'short': 'LINZ 0.125 m aerial 2010-11', 'citation': 'LINZ (2010-11). Bay of Plenty 0.125 m Urban Aerial Photos (2010-2011), CC BY 4.0, tile BD37_1000_1314. Used as a position/size check only. Registry img-09.', 'url': 'https://nz-imagery.s3.ap-southeast-2.amazonaws.com/bay-of-plenty/bay-of-plenty_2010-2011_0.125m/rgb/2193/collection.json'},
        {'id': 'ctx5', 'short': 'Esri World Imagery Wayback 2011-01-15', 'citation': 'Esri World Imagery (Wayback), 15 Jan 2011, zoom 18-19: wet/dry sand line = model shoreline y = 0. Registry img-15, img-16.', 'url': 'https://wayback.maptiles.arcgis.com/arcgis/rest/services/World_Imagery/WMTS/1.0.0/default028mm/MapServer'},
        {'id': 'R1', 'short': 'Focus RMG / BoPRC report', 'citation': 'Focus Resource Management Group (2013/14). Mount Maunganui Reef - Assessment of Management Options. Report for Bay of Plenty Regional Council (printed p6 crest and completion mid-2008; p21; p23 bed and crest unchanged; p28 built volume 2,800 m3; p29 bed fluctuates > 1 m).', 'url': BOPRC},
        {'id': 'R3', 'short': 'Raised Water Research Mount Maunganui page', 'citation': 'Raised Water Research. Mount Maunganui artificial reef page (ASR Installed image, multibeam 2007, built volume 2,800 m3). Accessed 2026-10-05.', 'url': 'https://raisedwaterresearch.com/spot/artificial-reef/new-zealand/north-island/mount-maunganui/'},
        {'id': 'R4', 'short': 'Scarfe 2008 thesis', 'citation': 'Scarfe, B.E. (2008). Oceanographic considerations for the management and protection of surfing breaks. PhD thesis, University of Waikato (datum MVD-53; Table 8-3 offshore distance 257-324 m; 2007 crest -1.25 m MSL; scour hole 7,500 m2; depth of closure 5-6 m).', 'url': 'https://hdl.handle.net/10289/2668'},
        {'id': 'R5', 'short': 'NIWA 2006 MHWS Bay of Plenty', 'citation': 'NIWA (2006). MHWS level for the Bay of Plenty. Client report HAM2006-133 (Bell, Goring et al.): MVD-53 = Chart Datum + 0.9622 m at Tauranga.', 'url': 'https://www.boprc.govt.nz/media/32572/NIWA-091119-MHWSlevelforBOP.pdf'},
        {'id': 'R6', 'short': 'LINZ standard port tidal levels', 'citation': 'LINZ. Standard port tidal levels, Tauranga row (page updated 8 Jun 2026; accessed 2026-10-06; private copy 3d/src/linz_standard_port_levels_Tauranga_excerpt.txt). LINZ website content.', 'url': 'https://www.linz.govt.nz/guidance/marine-information/tide-prediction-guidance/standard-port-tidal-levels'},
        {'id': 'R7', 'short': 'LINZ Moturiki readme', 'citation': 'LINZ. Notes about the Moturiki Annual Mean Sea Level Data (updated 16 Feb 2023): gauge zero 1.487 m below MVD-53; chart datum 4.103 m below BM BC84. Periods page: 3d/src/linz_standard_port_periods_excerpt.txt.', 'url': 'https://www.linz.govt.nz/sites/default/files/data/Moturiki_Readme.pdf'},
        {'id': 'R9', 'short': 'Moores 2006 NZ Geographic', 'citation': 'Moores, A. (2006). Artificial surf reefs - coming to a beach near you. New Zealand Geographic 78 (design: largest bags 3.5 m high x 50 m long, 660 m3; 4.5 m depth).', 'url': 'https://www.nzgeo.com/stories/artificial-surf-reefs-coming-to-a-beach-near-you/'},
        {'id': 'R10', 'short': 'SunLive 2014 removal', 'citation': 'Balvert, L. (2014). Time called on artificial reef. SunLive, 10 Nov 2014 (removal 25 Sep to 8-9 Nov 2014, NZ$87,000).', 'url': 'https://www.sunlive.co.nz/news/86837-time-called-on-artificial-reef.html'},
        {'id': 'R11', 'short': 'NZ Herald consent / washed ashore', 'citation': "NZ Herald / Bay of Plenty Times (2014) NZ's first artificial surf reef wiped out; (2023) Artificial reef washes ashore at Mount Maunganui.", 'url': 'https://www.nzherald.co.nz/nz/nzs-first-artificial-surf-reef-wiped-out/NYTRFDL22KDED3WOWQE5HO5MYQ/'},
        {'id': 'N1', 'short': 'Garmin Navionics SonarChart / Nautical Charts', 'citation': 'Garmin Ltd / Navionics (2026). Marine Maps viewer (SonarChart Maps and Nautical Charts, metres, zoom 17-18, Shallow-shading 0-10 m), centre -37.6447833, 176.2025908; accessed 2026-10-06; NOT FOR NAVIGATION; private research copy. Registry mount-maunganui-reef-img-19 to -22.', 'url': 'https://maps.garmin.com/en-US/marine?maps=another-brand&overlay=false&key=rcm3cdfz1zy2'},
    ]

    def P(par, val, unit, sid, meth, unc, est):
        return {'parameter': par, 'value': val, 'unit': unit, 'source_id': sid, 'method': meth, 'uncertainty': unc, 'estimated': est}
    model['provenance'] = [
        P('Plan outline, default version', '1,071 m2 (67.9 x 60.4 m), 5 polygons', 'canonical m', 'img1, ctx9 (img-08, img-04)', 'the -2.0 m CD contour of the 18 Jul 2013 multibeam survey read on the georeferenced Fig 3 (NZ-grid ticks), re-checked on Fig 5 (IoU 0.93)', '+-1-2 m on the edge; lower-bound footprint (8-15 % below the 80 x 70 m text)', False),
        P('Plan outline, version 2 (as-built toe)', '1,424 m2 (73.9 x 62.5 m), 3 polygons', 'canonical m', 'img3, img1 (img-10)', 'toe-level outline of the ASR Installed image registered onto Fig 3', 'scale +-6 %; datum of the image not stated', False),
        P('Position and frame', 'centroid -37.64478, 176.20259; y = 307.7 m from the shoreline; x toward 316.15, y toward 46.15', 'deg, m', 'img1, ctx5, img2', 'NZ-grid ticks -> EPSG:2106 -> canonical chain (explicit, no rotation function); shoreline = wet/dry sand line of the 2011-01-15 Esri image; aerial agrees to about 2 m', '+-2 m position; shoreline +-3 m (tide state of the image unknown)', False),
        P('Vertical frame', 'z = 0 at present MSL = CD + 1.13 m', 'm', 'R6', 'LINZ standard port Tauranga: MSL from 2006-2025 observations', '+-0.03 m; MVD-53 is 0.17 m lower', False),
        P('MVD-53 datum line', 'CD + 0.9622 m = z -0.168 m MSL', 'm', 'R5', 'NIWA 2006 Tauranga offset; MVD-53 is the datum of Scarfe 2008 and (assumed) of the ASR Installed image', '+-0.001 m', False),
        P('Tide levels', 'HAT +1.07, MHWS +0.83, MHWN +0.53, MSL 0, MLWN -0.56, MLWS -0.92, LAT -1.16', 'm MSL', 'R6', 'LINZ Tauranga row minus 1.13 (MHWS..MLWS predicted 2026-27; HAT/LAT 2000-2018)', 'annual variation 0.1-0.15 m', False),
        P('Crest (main bags)', '-0.9 CD = -2.03 MSL', 'm', 'R1 p6, p21; img-04, img-08', 'BoPRC: main-bag crest 0.8-1.0 m below CD; Fig 5 west block shallowest 5 % -0.80, south-arm median -1.35; BoPRC p23: crest of the main bags not changed significantly 2008-2013', '+-0.1 m (range 0.8-1.0)', False),
        P('Inner profile (rise above the -2.0 m contour)', 'RISE 0 / 0.30 / 0.50 / 0.70 / 0.85 / 0.95 / 1.05 / 1.10 m at 0 / 0.5 / ... / 3.5 m inside the contour', 'm', 'ctx9 (img-04)', '2013 DEM medians of the west block and south arm normalised to the crest, linear interpolation; r(d2) scales with the chosen crest', '+-0.1 m; idealised (no bag-by-bag relief)', True),
        P('As-built bed at the reef centre', '-4.0 CD (-5.13 MSL), selector -3.0 / -3.5 / -4.0 / -4.5', 'm', 'orchestrator decision 2026-10-06; R1 p23, R9, img-10', 'bed 3.0-4.0 m deep beside the north arm in 2008 (BoPRC p23), ASR Installed ring -4.46 CD (if MVD-53), consent 3.7-4.6 m, Moores 4.5 m (design). FLAG: 2013 survey -2.4 .. -3.3 CD and Navionics 2026 -2.76 CD are 1.0-1.6 m shallower; the stated 2,800 m3 matches a bed of -3.5 to -3.7', '+-0.5 m (range -3.0 .. -4.5)', True),
        P('Seabed shape outside the reef', 'Navionics SonarChart contours 1-8 m at y = 111, 242, 329, 399, 463, 546, 642, 728 m; %.2f m deep at the reef centre' % -zr, 'm CD', 'N1 (img-19..22)', 'shallow-shading edges = contours, median of 5 shore-normal transects; datum not stated, tested against the 2013 multibeam bed (RMS 0.30 m as CD, 0.78 as MVD-53, 0.95 as MSL)', 'contour position +-2-5 m; datum +-0.3 m; 2026 seabed, not 2008', False),
        P('Bed shift rule', 'S(y) = Pnav + (bed - Pnav(y_ref)) * clamp((y - 111.2)/(307.7 - 111.2), 0, 1)', 'm CD', 'assumption A6', 'nearshore (y < 111 m) keeps the Navionics profile; the offset is ramped in to the reef and kept seaward (slope as Navionics 1:61-1:96)', 'unknown; only matters away from the reef', True),
        P('Flank, default version (skirt)', '1:1 (H:V) from the -2.0 m contour to the bed (selector 0.25-2)', 'H:V', 'assumption A7; img-04 transects', '2013 transects: seaward side ~1:1, landward ~1:2, west-arm north edge ~vertical; the 2008 toe lies only 0.56 m (median) outside the contour, i.e. steeper than 1:1', 'run 0.25-2: volume at bed -4.0 = %.0f to %.0f m3' % (c_def['volume_bed-4.0_by_run']['0.25'], c_def['volume_bed-4.0_by_run']['2.0']), True),
        P('Flank, toe version (loft)', 'linear fraction between the toe (bed) and the -2.0 m contour', '-', 'assumption A8', 'z = S + (-2.0 - S) * dT/(dT + dout) in the toe minus the contour area', 'shape only; the volume depends on the bed', True),
        P('Seaward bed slope', '1:61 (2013 plane), 1:64-1:70 (Navionics 3-5 m)', 'H:V', 'img-04; N1; R1', 'plane fit of the 2013 bed through the reef; BoPRC range 1:60-1:110', '+-15 %', False),
        P('Volume check', 'model %.0f m3 (survey outline, skirt 1:1) and %.0f m3 (toe loft) at bed -4.0 vs 2,800 m3 stated; bed that gives 2,800 = %.2f / %.2f CD' % (v_s, v_t, c_def['bed_for_2800'], c_toe['bed_for_2800']), 'm3', 'R1 p28; R3; img-10', 'sum of heights above the local bed on the 0.5 m grid; even vertical flanks on the -2.0 outline hold %.0f m3 at bed -4.0' % c_def['vertical_wall_minimum_volume_bed-4.0_m3'], 'stated volume rounded; Installed grid gives 2,835-2,861 m3', False),
        P('Evidence layer: 2013 survey surface', 'hue-decoded Fig 5 DEM, 1 m grid', 'm CD -> m MSL', 'ctx9 (img-04)', 'hue -> colour-bar depth (mmr_lib.load_fig5), resampled to the canonical frame', '+-0.15 m; 2013 state, not as-built', False),
        P('Dry beach above the shoreline', '1:15 ramp', 'H:V', 'none', 'schematic only so the water plane meets land', 'not sourced', True),
    ]
    model['confidence_3d'] = {
        'level': 'medium',
        'reason': ('Plan, crest and tides are sourced: the outline is the -2.0 m contour of the 2013 multibeam survey (confirmed on a second raster and the aerial), the crest -0.9 m CD agrees with the BoPRC text and both survey figures, and the tide levels are LINZ values for Tauranga. '
                   'The weak links are the as-built bed (decision -4.0 m CD, +-0.5) and therefore the reef height (about 3 m) and the flank shape: every later source reads the bed 1.0-1.6 m shallower, and the stated 2,800 m3 is only reproduced with a bed of about %.2f to %.2f m CD. '
                   'The seabed outside the reef is the 2026 Navionics SonarChart (datum tested against the 2013 survey), not the 2008 seabed.' % (c_def['bed_for_2800'], c_toe['bed_for_2800'])),
        'reason_short': 'MEDIUM: outline, crest and tides sourced; the as-built bed (-4.0 +-0.5 m CD) and so the 3 m height are an unresolved decision (later sources 1.0-1.6 m shallower; 2,800 m3 needs about -3.6).'}
    model['inputs_status'] = {
        'plan': 'sourced - verified outline (medium): -2.0 m CD contour of the 18 Jul 2013 multibeam survey (default) and the 2008 as-built toe outline (version 2); not the 80 x 70 m text figure.',
        'crest': 'sourced - -0.9 m CD (0.8-1.0 below CD, BoPRC p6/p21, confirmed on Fig 3 / Fig 5); z = -2.03 m MSL.',
        'height_slopes': 'estimated - height about 3 m = crest to the chosen bed; flanks: 1:1 skirt (default, assumption) or toe loft; inner profile from the 2013 DEM.',
        'seabed': 'sourced + decision - Navionics SonarChart 2026 profile (datum tested) shifted to the as-built bed -4.0 +-0.5 m CD (decision; 2013 survey and Navionics read -2.4 to -3.3).',
        'tides': 'sourced - LINZ Tauranga standard port levels (CD), MVD-53 = CD + 0.9622 m (NIWA 2006); z = 0 at present MSL.'}
    return model
